name: Deployment Pipeline

on:
  push:
    branches: [master]
    
jobs:
  simple_deployemnt_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install yarn globally
        run: npm install --global yarn
      - name: remove package-lock.json to avoid lockfile inconsistencies
        run: rm package-lock.json
      - name: yarn install
        run: yarn
      - name: lint
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      
