name: Deployment Pipeline

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployemnt_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install yarn globally
        run: npm install --global yarn
      - name: remove package-lock.json to avoid lockfile inconsistencies
        run: rm package-lock.json
      - name: yarn install
        run: yarn
      - name: lint
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn test:e2e
          start: yarn start-prod
          wait-on: http://localhost:5000
      - name: deploy to heroku
        if: |
          github.event.name == 'push' && 
          !contains(join(github.event.commits.*.message, ' '), '#skip')
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'damp-shelf-71970'
          heroku_email: 'olowotemple@yahoo.com'
          healthcheck: 'https://damp-shelf-71970.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.
