name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Event name
        run: echo "${{ github.event_name }}"

      - name: Commit message
        run: echo "${{ join(github.event.commits.*.message, ' ') }}"

      - name: 'does commit message contain #skip?'
        run: echo "${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}"
