name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: does commit message contain skip?
        run: echo "${{ contains(join(github.event.commits.*.message, ' '), 'skip') }}"
      - name: only do this step if commit message does not contain skip
        if: |
          github.event.name == 'push' &&
          !contains(join(github.event.commits.*.message, ' '), 'skip')
        run: echo "Event name - push \n\n Commit message does not contain skip"

      # - name: does commit message contain skip?
      #   run: echo ${{contains(github.event.commits.*.message.join(' '), 'skip')}}
#         if: |
#           github.event_name == 'push' &&
#           !contains(github.event.commits.*.message.join(' '), 'skip')

# if: ${{!contains(github.event.commits.*.message.join(' '), 'skip')}}
